CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"
IMAGE_PLACEHOLDER = "<image-placeholder>"


FIM_IMAGE_TOKEN_INDEX = -300
FIM_IMAGE_TOKEN = "<fim_image>"
DEFAULT_FIM_PREFFIX = "<fim_prefix>"
DEFAULT_FIM_SUFFIX = "<fim_suffix>"
DEFAULT_FIM_MIDDLE = "<fim_middle>"
DEFAULT_FIM_MASK = "<fim_mask>"
DEFAULT_FIM_PREFFIX_END = "</fim_prefix>"
DEFAULT_FIM_SUFFIX_END = "</fim_suffix>"
DEFAULT_FIM_MIDDLE_END = "</fim_middle>"
